### PR TITLE
Additionnal steps

### PR DESCRIPTION
**Pull request by xavierraffin**
Add two simple checks.

### CODE REVIEW

**Comment by nlehuby** [comment]
* Can you please uncapitalize the first word of your steps ? The others steps have their first letter lowercased
* there is an indentation issue with your last commit
* maybe add an example scenario in the idf public feature ?

**Comment by xavierraffin** [comment]
OK I will (probably next week). I will do my best on Idf, even if I know this area not so much.
Glad you accept PR on this project.

Dou you have any strategy or rules about acceptable steps ?
Our data team have a lot of idea, and I would like to now if I need to cool down their creativity in some ways.

**Comment by nlehuby** [comment]
I'm not comfortable with the fact that the test must be true for each journey for the step to pass. Is it really what you wanted to do ?
As there is no step (yet ?) to really tweak the parameters for the journey query, we often get many journeys and they may not have the same first stop and street_network section at the beginning.

**Comment by nlehuby** [comment]
We now have test steps to compute street_network-only journeys (see https://github.com/CanalTP/navitia-checker/blob/master/public_features/fr_idf.feature#L62)
do you want to re-write your test about the first walk section length ?

**Comment by eturck** [comment]
Sorry for the delay in responding. During our last meeting with Kisio somebody asks me if we had an update on this PR.
Since @xavierraffin has left Tisséo we haven't had time to work on navitia-checker, mainly because the person who was supposed to be working on a bunch of automated testing stuff for us cancelled its intership at the last time.
For now, since there is some problem with the current PR, you can close it.
Further in the future I'm sure we are going to pick this project up again and we will use the new tools provided. If then we are still missing something, we will happily contribute to this project :).

**Comment by nlehuby** [comment]
ok, thanks for your response.

**Pull request closed without merging**
